# Generated by Django 6.0 on 2026-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_account_type_loan_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappuser',
            name='default_currency',
            field=models.CharField(default='inr', max_length=8),
        ),
    ]
